### ISSUE TITLE
Improve the Readability of the code

### ISSUE THREAD

**Issue by ImaginedTime** [ImaginedTime/ParticlesJS.js#2]
Improving the code Readability. The code contains some variables that are not to apt for the code, like the the data that is passed is through the parameter called Variables, which can be switched out to rather use something like props, etc. Similar code changes can be done, so as to make the code better

**Comment by shine-n-rize** [comment]
Hey @ImaginedTime could you assign this issue to me?

**Comment by ImaginedTime** [comment]
Okay, I am assigning this to you

**Comment by 4artiseth** [comment]
Hi, I was working on this project and have finished it with
 Improved readibility
 Better variables
 Made it easier to maintain
 Added necessary HTML document not in the repo. 
 Best coding practices with clean code
Please assign it to me so i can pull the request.
@ImaginedTime

**Comment by ImaginedTime** [comment]
> Hi, I was working on this project and have finished it with Improved readibility Better variables Made it easier to maintain Added necessary HTML document not in the repo. Best coding practices with clean code Please assign it to me so i can pull the request. @ImaginedTime

Thank you for your participation as well.

**Comment by ImaginedTime** [comment]
@4artiseth You had improved the readability, but the part of the code for drawing different shapes had been rmeoved completely. Please have a look into it

**Comment by ImaginedTime** [comment]
@4artiseth Please add that part of the code and send a pr
