### ISSUE TITLE
Document the Code

### ISSUE THREAD

**Issue by ImaginedTime** [ImaginedTime/ParticlesJS.js#3]
The code itself needs some documentation. Please read the code and add valuable comments

**Comment by khushpreetsinghb** [comment]
I am new to open source, I want to work on this issue. Can you please assign this to me.

**Comment by ImaginedTime** [comment]
> I am new to open source, I want to work on this issue. Can you please assign this to me.

Okay, I am assigning this to you

**Comment by khushpreetsinghb** [comment]
I have started working on it. So, assign this to me.

**Comment by ImaginedTime** [comment]
I have already assigned this to you

**Comment by khushpreetsinghb** [comment]
Then you have unassigned this issue.

**Comment by ImaginedTime** [comment]
It is assigned, please have a look. I've redone it, for your reassurance.

**Comment by khushpreetsinghb** [comment]
It is showing that you have assigned and unassigned this issue.
I will do it, no worries.
